; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-core2]
; without explicit version it uses pioarduino/platform-espressif32 @ 53.3.13
; which causes the esp to coredump with esp_core_dump_flash: Core dump flash config is corrupted
platform = espressif32 @ 7.0.1
board = m5stack-core2
framework = arduino
lib_deps = 
	FS
	Wire
	m5stack/M5Unified@^0.2.17
	gilmaimon/ArduinoWebsockets@^0.5.4
	bblanchon/ArduinoJson@^6.21.6
	ivanseidel/LinkedList@0.0.0-alpha+sha.dac3874d28
	adafruit/Adafruit MCP23008 library@^2.1.0
monitor_speed = 115200
